#!/usr/bin/env bash
ssh -i "~/.ssh/nhantranvan.pem" ubuntu@18.139.108.251 '''/bin/bash -c "cd /home/ubuntu/movielearning-server \
        && git pull origin main \
        && (docker rm -f movielearning-server || true) \
        && docker build -t tranvannhan1911/movielearning-server . \
        && docker run -d -p 8000:8000 --name movielearning-server tranvannhan1911/movielearning-server \
        && docker exec movielearning-server python3 manage.py migrate "'''

# && (docker rmi -f $(docker images -a | grep tranvannhan1911/minimart-server | awk "{print $3}") || true) \