# Generated by Django 4.1.6 on 2023-02-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
