# Generated by Django 4.1.6 on 2023-02-03 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_showtime_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='id',
        ),
    ]
