# Generated by Django 4.0.9 on 2023-02-13 02:03

import bson.objectid
import core_movie.models
from django.db import migrations, models
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('mongo_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('id', models.IntegerField(default=0)),
                ('display_name', models.CharField(default='abc', max_length=255)),
                ('name', models.CharField(default='abc', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Localize',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('lang', models.CharField(default='abc', max_length=5)),
                ('title', models.TextField(default='abc')),
                ('overview', models.TextField(default='abc')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('title', models.CharField(default='abc', max_length=255)),
                ('apiId', models.IntegerField(default=0)),
                ('type', models.TextField(default='abc')),
                ('poster_path', models.TextField(default='abc')),
                ('backdrop_path', models.TextField(default='abc')),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
                ('trailer_key', models.CharField(default='abc', max_length=255)),
                ('overview', models.TextField(default='abc')),
                ('localizes', djongo.models.fields.ArrayField(model_container=core_movie.models.Localize, model_form_class=core_movie.models.LocalizeForm)),
                ('genres', djongo.models.fields.ArrayField(model_container=core_movie.models.Genres, model_form_class=core_movie.models.GenresForm)),
                ('level', models.IntegerField(choices=[(1, 'FRESHER'), (2, 'JUNIOR'), (3, 'SENIOR'), (4, 'MASTER')], default=1)),
                ('number_of_seasons', models.IntegerField(default=0)),
                ('number_of_episodes', models.IntegerField(default=0)),
                ('video_url', models.TextField(default='abc')),
                ('link_mp4', models.TextField(default=None)),
                ('dateFirstPublished', models.DateTimeField(default=django.utils.timezone.now)),
                ('movie_id', models.CharField(default=' ', max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zalo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('sub', djongo.models.fields.ArrayField(model_container=core_movie.models.Translate, model_form_class=core_movie.models.TranslateForm)),
                ('movie_id', models.CharField(default=' ', max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('cueStart', models.IntegerField()),
                ('transcript', models.TextField()),
                ('cueEnd', models.IntegerField()),
                ('transcript_vi', models.TextField()),
                ('seq', models.IntegerField(default=0)),
            ],
        ),
    ]
