# Generated by Django 4.0.9 on 2023-03-02 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MovieGroup',
            fields=[
                ('title', models.CharField(default='haha', max_length=255, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('movies', models.ManyToManyField(blank=True, to='core_movie.movie')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
