# Generated by Django 4.0.9 on 2023-02-13 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_movie', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileUser',
        ),
    ]
